### PR TITLE
Enhance MeCab kinds

### PR DESCRIPTION
**Pull request by kampersanda**
This PR 
 - added `unidic-mecab v2.1.2` in MeCab evaluation and specifications of dictionary versions;
 - changed the optimization flag from `-O2` into `-O3` to keep consistency with Vibrato and Vaporetto;
 - added `.clang-format` to maintain the c++ format.

### CODE REVIEW

**Review by vbkaisetsu — COMMENTED** [review]
I have already merged #2, but on second thought, it would be better to keep only the representative settings and delete the others.
If we cover minor differences such as different dictionaries and models, the comparison script would become infinitely larger.

**Comment by kampersanda** [comment]
@vbkaisetsu

I think representative dictionaries are `ipadic-mecab v2.7.0` and `unidic-mecab v2.1.2`. For example, lindera supports these two dictionaries, and sudachi's dictionary is designed based on `unidic-mecab v2.1.2`.

What do you think about keeping these two dictionaries?

**Comment by kampersanda** [comment]
On second thought, it seems most reasonable to include `ipadic-mecab v2.7.0` and `unidic-cwj v3.1.0` based on the policy of evaluating only the latest versions. This is because the number of dictionaries is easily limited if only the latest version is considered.

**Review by vbkaisetsu — COMMENTED** [review]
I think unidic-mecab v2.1.2 is the best.

Also, could you remove .clang-format for now?
This repository uses many languages and C++ is only partially used.

**Comment by kampersanda** [comment]
@vbkaisetsu I did that. https://github.com/legalforce-research/tokenizer-speed-bench/pull/4/commits/00acde6999678f313a3d012fe7f1ac90a9e81604

**Comment by vbkaisetsu** [comment]
Sorry, I misunderstood.
Could you remove unidic-mecab-2.1.2 and add unidic-cwj-3.1.0?

**Comment by kampersanda** [comment]
@vbkaisetsu No problem. I did that https://github.com/legalforce-research/tokenizer-speed-bench/pull/4/commits/cc3ad2e4f9368342925a69971badb69b0b76d134

**Review by vbkaisetsu — APPROVED** [review]

**Pull request merged**
